Repository mia-platform/design-system, pull requests merged in 2023-10, with the labels that each got.

#89 ci: release workflow
  .github/release.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  package.json
  src/components/Button/__snapshots__/Button.test.tsx.snap
Labels: github_actions

#115 Fix(PDS-63): segmented styles
  src/components/SegmentedControl/SegmentedControl.module.css
  src/components/SegmentedControl/SegmentedControl.stories.tsx
Labels: enhancement

#133 fix: theme default style
  src/components/ThemeProvider/utils/__tests__/__snapshots__/themeDefaultStyle.test.ts.snap
  src/components/ThemeProvider/utils/themeDefaultStyle.ts
Labels: bug

#144 fix: segmented control disabled and vertical items
  .eslintrc.cjs
  src/components/SegmentedControl/SegmentedControl.module.css
  src/components/SegmentedControl/SegmentedControl.test.tsx
  src/components/SegmentedControl/SegmentedControl.utils.ts
  src/components/SegmentedControl/__snapshots__/SegmentedControl.test.tsx.snap
Labels: bug

#152 fix: segmented control pass event to onChange, fix button tests
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/SegmentedControl/SegmentedControl.test.tsx
  src/components/SegmentedControl/SegmentedControl.tsx
Labels: bug
