Repository mia-platform/design-system, pull requests merged in 2024-01, with the labels that each got.

#251 ci: remove parallel builds
  .github/workflows/test.yml
Labels: github_actions

#256 fix: removed assets folders from test coverage
  jest.config.js
Labels: bug

#263 fix: Card paddings
  src/components/Card/Card.module.css
Labels: enhancement

#252 docs: contributing
  CONTRIBUTING.md
Labels: documentation

#272 fix: Table export
  src/index.ts
Labels: bug

#275 fix: added exported components check to pull requests template
  .github/pull_request_template.md
Labels: documentation
